### ISSUE TITLE
Annotations are stored on the PDF Document

### ISSUE THREAD

**Issue by simonv3** [RichardLitt/awesome-annotation#3]
Ex: http://jsfiddle.net/seikichi/RuDvz/2/

Does anyone have any documentation for this?

**Comment by RichardLitt** [comment]
I'm confused. You mean like native formats such as preview?

**Comment by simonv3** [comment]
Across the internet I'm finding references to the fact that people are programmatically adding annotations to PDFs as part of the API available to working on the PDF, presumably meaning that the PDF itself contains those annotations. That's what that fiddle above hints at with `page.getAnnotations()`

I'm wondering whether there's good documentation for this API available. 

PDF.js alludes to this being possible in general in their wiki: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations, just that they don't support it. 

Which leads me to believe (and I could be wrong) that it's possible to add annotations directly to a PDF, which would mean not having to store them anywhere if you own the PDF yourself. (Which is what's different between something like simonv3/annotate, where you upload the documents, vs Beagle, where the you're annotating on top of the publicly available documents)

**Comment by RichardLitt** [comment]
I bet it is possible. I don't know how to do it. Beagle also allowed annotating documents you own; having an option to store on the PDF, or to import comments already on PDFS, would be awesome.

**Comment by RichardLitt** [comment]
I'm not sure that this discussion has anywhere to go: closing this.
